#!/usr/bin/env python3
"""Render 「中國之心」 from a brush-calligraphy TTF into a 1-bit mask compiled
into the dgds engine (hoc_title_glyphs.h). The engine blits this mask with a
gold fill + dark outline under the片頭 "HEART OF CHINA" title (cjk.cpp
drawTitleSubtitle). Calligraphy at large size, decoupled from the 24x24 Big5
bitmap font.

Default font: AR PL UKai (楷書 brush) — the only locally-available brush font
that covers all four *traditional* glyphs (the open-source 行書/草書 fonts only
have 中之心, not 國). Swap --font to restyle; rerun to regenerate.

Usage: python3 tools/build_title_mask.py [--font PATH] [--size N] [--gap N] [--out HDR] [--png PREVIEW]
"""
import argparse
from PIL import Image, ImageFont, ImageDraw

TEXT = "中國之心"
DEFAULT_FONT = "/usr/share/fonts/truetype/arphic/ukai.ttc"


def render(font_path, size, gap):
    font = ImageFont.truetype(font_path, size)
    # Render each glyph tight-cropped, then composite on a common baseline with a
    # fixed gap so the spacing is even (calligraphy advances are uneven).
    cells = []
    for ch in TEXT:
        big = Image.new("L", (size * 2, size * 2), 0)
        ImageDraw.Draw(big).text((size // 2, size // 2), ch, font=font, fill=255)
        bbox = big.getbbox()
        cells.append((big.crop(bbox), bbox))
    top = min(b[1] for _, b in cells)
    bot = max(b[3] for _, b in cells)
    H = bot - top
    W = sum(c.width for c, _ in cells) + gap * (len(cells) - 1)
    sheet = Image.new("L", (W, H), 0)
    x = 0
    for (c, b) in cells:
        sheet.paste(c, (x, b[1] - top))
        x += c.width + gap
    return sheet


def emit_header(sheet, out, font_path, size):
    W, H = sheet.size
    bpr = (W + 7) // 8
    px = sheet.load()
    rows = []
    for y in range(H):
        row = bytearray(bpr)
        for x in range(W):
            if px[x, y] > 110:
                row[x >> 3] |= 0x80 >> (x & 7)
        rows.append(row)
    lines = [
        "// Generated by tools/build_title_mask.py — DO NOT EDIT.",
        f"// 「{TEXT}」 from {font_path.split('/')[-1]} @ size {size}.",
        "// 1bpp MSB-first mask; cjk.cpp drawTitleSubtitle() blits it (gold fill + dark outline).",
        f"static const int HOC_TITLE_W = {W};",
        f"static const int HOC_TITLE_H = {H};",
        f"static const int HOC_TITLE_BPR = {bpr};",
        "static const unsigned char HOC_TITLE_BITS[] = {",
    ]
    for r in rows:
        lines.append("\t" + ",".join(str(b) for b in r) + ",")
    lines.append("};")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    return W, H, bpr


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--size", type=int, default=52)
    ap.add_argument("--gap", type=int, default=5)
    ap.add_argument("--out", default="scummvm-src/engines/dgds/hoc_title_glyphs.h")
    ap.add_argument("--png", default="/tmp/hoc_title_preview.png")
    a = ap.parse_args()
    sheet = render(a.font, a.size, a.gap)
    # preview: gold-on-copper so it reads like the in-game look
    prev = Image.new("RGB", (sheet.size[0] + 20, sheet.size[1] + 20), (150, 80, 40))
    g = Image.new("RGB", sheet.size, (245, 208, 120))
    prev.paste(g, (10, 10), sheet)
    prev.save(a.png)
    W, H, bpr = emit_header(sheet, a.out, a.font, a.size)
    print(f"{a.font.split('/')[-1]} size={a.size}: mask {W}x{H} bpr={bpr} -> {a.out}")
    print(f"preview -> {a.png}")
